server:
  port: 8094
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://registry-service:8761/eureka}
spring:
  application:
    name: cookbook-service
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t
  boot:
    admin:
      client:
        url: http://localhost:8086