spring.datasource.url: jdbc:h2:file:~/data;DB_CLOSE_ON_EXIT=FALSE

server:
  port: 8091
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://registry-service:8761/eureka}
spring:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: profile-service
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t
  boot:
    admin:
      client:
        url: http://localhost:8086